<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hello_my-password-input</name>
   <tag></tag>
   <elementGuidId>71e1cfb1-c3e7-41f8-9de5-03523fe05165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#my-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='my-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3d9cac8-2cf9-4191-aea4-2f2985f5f95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e86a77d-5a9a-435b-b5fc-c67bc5dc62ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input your password here</value>
      <webElementGuid>36feb3c1-fa79-4894-ab0c-63b84372ee6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>my-password-input</value>
      <webElementGuid>9f1cba25-9509-4f70-8cc8-7579f614496b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SecurityPhrase---login-input---AwPq0 SecurityPhrase---login-input-font---14Asi</value>
      <webElementGuid>cd56bfec-00ed-49af-b636-90f303ba0feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>my-guid</name>
      <type>Main</type>
      <value>8e9890d2-d455-4d42-85a0-a61b6caf8b28</value>
      <webElementGuid>4d5d3b8d-0814-4bda-a137-73b1da894af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be973b7a-f8a6-43ec-9e18-f2863bb983b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>2f97f4a4-ab67-4d6d-9f99-0f7de94491f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6a1395b1-8b50-4fcf-bef2-f0c3f1c3c507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2c2e7b2a-6c28-4982-a1b3-6765199462b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5d011a4f-b25a-4538-b96b-41aa8b766aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-password-input&quot;)</value>
      <webElementGuid>31e1f07e-4891-4868-8789-c48a26b0383d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='my-password-input']</value>
      <webElementGuid>fdbacf31-0107-4d6a-ac13-3be536b4bb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>c4b291d0-940b-4ee6-9b02-a7311f5d7210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e8812264-c1aa-4b29-b601-8c9bae537c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Input your password here' and @id = 'my-password-input']</value>
      <webElementGuid>abfa6913-8758-4be0-9880-ec0ab3e7c47f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
