<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thank you for using Maybank2u</name>
   <tag></tag>
   <elementGuidId>f8c6fa94-9d74-48e7-8ec1-9691a8dbb2c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header2']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63c5cc15-485c-45a0-9631-217cfcd8b317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for using Maybank2u</value>
      <webElementGuid>d5277bdc-2697-4dcc-95b8-9c65a962151e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header2&quot;)/span[2]</value>
      <webElementGuid>01fa7e6d-a096-4359-b947-e53c9e899f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header2']/span[2]</value>
      <webElementGuid>25429cd6-7071-4e69-8d5d-47021a851a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have logged out!'])[1]/following::span[1]</value>
      <webElementGuid>3b49be2a-b776-4247-9c74-b8dc3940c1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Here', &quot;'&quot;, 's your receipt.')])[1]/following::span[3]</value>
      <webElementGuid>dd33c4f4-42a2-427d-9c6f-3aaf6d53b7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVITY DETAILS'])[1]/preceding::span[1]</value>
      <webElementGuid>7dd7051a-fd3f-4278-9500-b84e617b19bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATE'])[1]/preceding::span[1]</value>
      <webElementGuid>9741a711-7ac6-4fd9-a747-96dc817939d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you for using Maybank2u']/parent::*</value>
      <webElementGuid>f4f85957-db92-4d6a-be85-f2e251b42e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>4083c07f-0a80-4a33-a8e4-9457e33aff12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Thank you for using Maybank2u' or . = 'Thank you for using Maybank2u')]</value>
      <webElementGuid>6c5afca1-ceab-407a-8bf8-b1f1ae36bfd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
