<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TRANSFER</name>
   <tag></tag>
   <elementGuidId>6f5c608d-4c8c-4f09-8e8a-85dd8fc3cde4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d63b07b4-ec91-4b5f-9f2b-86208a0babb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PayNavigation---typeName---3lyPM</value>
      <webElementGuid>0a638c67-2d8c-4b54-af33-2ae0d7397bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRANSFER</value>
      <webElementGuid>f748ec68-86c9-417c-916e-adbe9a906905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTransactions&quot;)/div[@class=&quot;Transactions---container---3sqaa&quot;]/div[1]/div[@class=&quot;container-fluid PayNavigation---container---3nMJB&quot;]/div[@class=&quot;PayNavigation---navigation---3RD23&quot;]/div[@class=&quot;PayNavigation---navigationContent---2M_93 col-lg-8 col-md-10 col-xs-12&quot;]/div[@class=&quot;PayNavigation---row---3Pgej PayNavigation---mobile---wdWul&quot;]/div[@class=&quot;PayNavigation---nav-tabs---pHNAS&quot;]/div[@class=&quot;PayNavigation---desktopcontainer---4iWXT&quot;]/div[@class=&quot;PayNavigation---typeName---3lyPM&quot;]</value>
      <webElementGuid>58271bee-c789-46c5-ba77-1fefc6e8d6e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTransactions']/div/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>6e397b2f-baa4-4cac-878b-f97c6a87f7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAY'])[1]/following::div[3]</value>
      <webElementGuid>740b7e39-2d32-4e23-9d4f-258a5bc111e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RELOAD'])[1]/preceding::div[1]</value>
      <webElementGuid>758f24d3-7fa5-4513-b353-56923a2b8466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REQUEST'])[1]/preceding::div[4]</value>
      <webElementGuid>5a3c55ee-ad39-4248-9bea-e7706bfa02f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRANSFER']/parent::*</value>
      <webElementGuid>ebd2d645-e5fb-4245-9d4d-9fcbb1aee657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>c0846bce-037d-4463-8e56-7e3893baa935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TRANSFER' or . = 'TRANSFER')]</value>
      <webElementGuid>4b38bf29-7664-4ad8-b852-3cc7fef10f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
